// Generated by CoffeeScript 1.6.3
var ATModem, ATSerialDevice, Module, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Module = require('coffeescript-module').Module;

ATSerialDevice = require('./at-serial-device').ATSerialDevice;

exports.ATModem = ATModem = (function(_super) {
  __extends(ATModem, _super);

  function ATModem() {
    _ref = ATModem.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  return ATModem;

})(ATSerialDevice);
